- _datasets/10.23698/aida/sprob20.md
> Changed hidden to no

- .github/ISSUE_TEMPLATE/data_sharing_routine.md
Added zenhub issue template checklist for AIDA data-sharing routines.
> Added issue template

- .github/ISSUE_TEMPLATE/data-sharing-routine.md
> Updated issue template

- about/help/index.md
- services/index.md
Added instructions to download large amounts of data using rclone in the help section.
> Added rclone instructions

- _datasets/10.23698/aida/lesser.md
aida-license is changed to aida-by-license and reference number 1 deleted
> aida-license fixed and reference number 1 deleted

- _datasets/10.23698/aida/micromen.md
> Stain changed

- _datasets/10.23698/aida/micromen.md
- Github repos were added into the section "Kernels"
> Kernels section added

- _datasets/10.23698/aida/micromen.md
Changed hidden status of micromen dataset to visible
> Changed Micromen dataset status to visible

- _datasets/10.23698/aida/micromen.md
- Added "File formats"
- Fixed example image
- Changed modality to "MR"
- Arranged scanners
- updated sctid to direct to "brain" page
- Updated keywords, added radiology
- Updated date published and modified
- Made it public
> Micromen fixed and published

- services/index.md
Fixed PACS link on the services page
> Fixed PACS link

- _datasets/10.23698/aida/bccc.md
- _datasets/10.23698/aida/brmbr.md
- Created new dataset page for BRMBR
- Created new dataset page for BCCC
> Creating 2 new dataset landing pages

- _datasets/10.23698/aida/brln.md
- Discarded authors' names from AIDA BY CA license
> changes in AIDA BY CA license

- _datasets/10.23698/aida/bccc.md
- _datasets/10.23698/aida/brln.md
- size in bytes changed in bccc
- AIDA by license is fixed in bccc
- a sentence discerded in brln
> bccc and brln updated

- _datasets/10.23698/aida/bccc.md
- Generic Papar1 added
- page published - not hidden anymore
> Paper1 added

- _datasets/10.23698/aida/bccc.md
- _layouts/dataset.html
- reloading the page when one clicks on the "Paper 1" is fixed
> Paper link fixed

- _datasets/10.23698/aida/bccc.md
- wsi number changed from 1831 to 1832 in description
- size updated
- scan number updated
> wsi number chaged

- _datasets/10.23698/aida/brln.md
- changes made in description in BRLN page
> change in description

- _datasets/10.23698/aida/micromen.md
- Lund University as a copyright holder added in micromen page
> copyright holder updated

- _datasets/10.23698/aida/bccc.md
- _datasets/10.23698/aida/micromen.md
- _datasets/10.23698/aida/sprob20.md
- bccc - coauthorship:yes fixed and licence by ca changed to license by
- micromen - coauthorship:yes fixed
- sprob20 - bccc - coauthorship:yes fixed and licence by ca changed to license by
> license fixed for bccc micromen sprob20

- _datasets/10.23698/aida/bccc.md
> Adding new citation to BCCC

- prio/index.md
- wrist and shoulder added to 6. article
> data acquisition priorities updated

- index.md
- support/index.md
I added some stuff to address what we talked about so far, mainly with basis in the slide deck for the Tuesday meeting. This is very much a brain dump from me. @eryl please feel free to edit to your liking!
Fine by me to merge this into main; it has the usual disclaimers about "plans", "intentions" and "will be updated". Or we can keep working in a branch. Merging before the Tuesday meeting is a nice-to-have, for the others to easily peruse at their leisure. (It is not a must-have:)
Tagging the rest of you since you are already involved in support of various kinds, so you can see what's going on and contribute input if you want!
> Add first draft support page.

- _datasets/10.23698/aida/sr2023.md
- Added a paper to the references of the dataset
> Adding citation to sr2023

- prio/index.md
- added elbow to the priority list
> Adding elbow to priority list

- support/index.md
Removed a lot of the temporary wording and rephrased things to how the current status.
> Updated the support web page to not be in a preview mode

- _datasets/10.23698/aida/ejr2023.md
- Radiology added to the keywords
> keywords changed

- _datasets/10.23698/aida/ejr2023.md
- Orcid ID of Teo Stukan added
> adding orcid id

- prio/index.md
Add "Small datasets containing synthesized clinical imaging data" as lowest prio item, resulting from AIDA management interpretation[1] of clinical council discussion[1] and decision[2].
[1] https://nbisweden.slack.com/archives/C035RR86TMJ/p1699363126700179 
[2] https://docs.google.com/document/d/1mGlj5V1ptRr7afV8-wo7G4TGyYHw9ZWVA5kzLeuLJEs/edit#heading=h.l8w8jbgvttcn
[3] https://docs.google.com/document/d/1mGlj5V1ptRr7afV8-wo7G4TGyYHw9ZWVA5kzLeuLJEs/edit#heading=h.37znvw3z1x66
> Update prio list

- prio/index.md
- Approval date of the priority list updated
> Approval date changed

- _datasets/10.23698/aida/synthetic/brgandi.md
- _datasets/10.23698/aida/synthetic/shbamri.md
- brgandi scan numbers corrected
- brgandi aida-by-license link fixed
- shbamri [1] links fixed
- shbamri aida-by-license link fixed
- shbamri image titles added
> New synthetic dataset

- about/aida/index.md
Caroline found some broken links, now fixed.
> Fix links on the About AIDA page.

- call_for_help/index.html
- call_for_help/index.md
This form is not meant to be support form as of now. 
First, for test purposes, how to send request to redmine and see where it ends.
Then, we need to figure it out how to send support request instead of sending data submission request form.
Finally, form needs to be updated with the related sections.
> Call for help form

- jobs/2024-02-14-devops-engineer/index.md
- jobs/2024-03-19-devops-engineer/index.md
- jobs/index.md
Job ad is now out, lets push it everywhere!
> Devops job ad

- _datasets/10.23698/aida/ctpel.md
Added Vietnam to CTPEL dataset
> added vietnam to the metircs

- prio/index.md
2 new data type have been added to the prio list:
- Pathology and radiology data from glioma, such as GBM and pHGG.
- Hyperspectral images of skin tumors.
> priority list updated

- prio/index.md
> changing the date of prio list approval

- _includes/bibtex_citation.html
- _layouts/dataset.html
- _layouts/default.html
Added a feature to automatically generate BibTeX citations at the end of each dataset page. Users can now easily copy the citation for their academic work.
Changes made:
- Generate BibTeX entry from dataset metadata.
- Display citation in a 'Citation' section at the bottom of the dataset page.
- Include a 'Copy' button for easy use.
Tests:
- Checked BibTeX is generated correctly for different datasets.
- Ensured the 'Copy' button works.
Please review and let me know if anything else is needed.
> Bibtex feature

- preview/dsp.html
This works locally. I understand that this is what the plugin produces anyway, and it's seems easier to just do this manually for now.
> Manual redirect.

- _datasets/10.23698/aida/ctpel.md
Australia has been added to CTPEL
> australia added

- _datasets/10.23698/aida/lnco.md
- _datasets/10.23698/aida/lnco2.md
Singapore has been added to the shared countries for LNCO, LNCO2
> singapore added

- assets/css/style.scss
Also shrink font (like main content) for narrow screens.
Lightweight workaround for now.
> Move main menu left aligned of main content.

- _events/2024-09-03-aida-days-technical-workshop.md
I want to showcase this content to SG today. Looks ok?
> Info on tech workshop

- _datasets/10.23698/aida/bccc.md
- description has been updated as they uploaded more images
> updating bccc description

- data-science-platform/examples/gpu-sd-iaas-jupyter/index.md
This updates the demo by clarifying some things, updating them to the current state and improve some of the commands (like only allowing tightvnc to listen to connections from localhost).
> Updated the DSP demo

- _events/2025-03-19-data-science-platform-launch-party.md
- One more presentation is added to the program
> changing the event program

- _datasets/10.23698/aida/ctskull.md
- _datasets/10.23698/aida/lund-probe.md
- added Slovakia to the shared countries of CTSKULL
- created a new dataset webpage which is hidden right now
> updating the map and creating a new dataset

- _datasets/10.23698/aida/lund-probe.md
Added small section about the github repo for the dataset
> Added link to the github repo

- data-science-platform/hardware/index.md
Updated the hardware info to a more compact table (and made the information easier to update as a dynamic table). Also added missing information for DGX-2
> Updated the hardware info for verdi and dgx-2

- Gemfile
- _datasets/10.23698/aida/lund-probe.md
Fixed som text entries according to Christians suggestions
> Fixed some text

- policy/dsp-privacy-policy.md
- policy/index.md
> Add privacy policy for DSP

- _datasets/10.23698/aida/lund-probe.md
Added a citation to the article Christian asked for
> Added citation to the arxiv article

- _datasets/10.23698/aida/lund-probe.md
The em dash messed up the DOI API thingie, this should hopefully fix it
> Fixed the em dash

- _datasets/10.23698/aida/bccc.md
- _datasets/10.23698/aida/drbr.md
Updated the shared countries for two datasets
> Added new countries-shared

- _events/2025-03-19-data-science-platform-launch-party.md
Added speaker for the AIDA presentation
> Added speaker

- _datasets/10.23698/aida/ctpa.md
- _datasets/10.23698/aida/ctpel.md
- _datasets/10.23698/aida/drli.md
- _datasets/10.23698/aida/drske.md
Updated the link to the "Working with DICOM" documentation to the new location
> Fixed broken link

- about/index.md
This PR solves [this](https://app.zenhub.com/workspaces/cortex-6374c04dd78d631b359d99e5/issues/gh/nbisweden/aida-data-hub/961) issue.
> Update support contact information on contact page

- _training-events/2024-09-04-dali-workshop.md
- _training-events/2025-02-05-ray-toolkit-workshop.md
- _training-events/2025-02-06-easy-to-use-genai-workshop.md
- training/index.md
This PR solves [this](https://app.zenhub.com/workspaces/cortex-6374c04dd78d631b359d99e5/issues/gh/nbisweden/aida-data-hub/881) issue.
> Add aida days training

- _datasets/10.23698/aida/lund-probe.md
Link to gdrive as we do for other DSA templates.
> Update DSA template link.

- _support-projects/2025-03-21-urine-cytology.md
Short page about support project
> Added urine cytology project page

- _datasets/10.23698/aida/synthetic/brgandi.md
Updated brgandi as per card #996, changed provider order to have active e-mail adress first. Updated access request blurb to be for research and educational use.
> Updated provider list and controlled access

- _datasets/10.23698/aida/lund-probe.md
Update lund-probe with country TH, Thailand
> Update lund-probe with country TH, Thailand

- _datasets/10.23698/aida/drov.md
Update drov.md with new country, GB
> Update drov.md with new country, GB

- _datasets/10.23698/aida/drbr.md
Update drbr.md with new country, AU
> Update drbr.md with new country, AU

- datasets/scapis/index.md
Some clarifications for scapis procedure.
> Update to instructions for SCAPIS

- _datasets/10.23698/aida/lund-probe.md
Update lund-probe with new country, Canada
> Update lund-probe with new country, Canada

- _datasets/10.23698/aida/bccc.md
Added citation for the BCCC dataset
> Added citation for BCCC dataset

- _datasets/10.23698/aida/synthetic/brgandi.md
Update brgandi with a new country SA, Saudi Arabia
> Update brgandi with a new country SA, Saudi Arabia

- services/index.md
This PR updates the prices in the Service list on Access and pricing.
> Update service pricing
